Repository UNIZAR-30246-WebEngineering/lab2-rpc-over-http, pull requests merged in 2021-11, with the labels that each got.

#36 Primary goal
  README.md
Labels: enhancement

#38 Primary goal
  README.md
Labels: enhancement

#40 Gift review
  README.md
Labels: enhancement, gift

#41 Primary Goal
  README.md
Labels: enhancement

#42 Primary Goal
  README.md
Labels: enhancement

#44 Primary Goal
  README.md
Labels: enhancement

#50 Primary goal
  README.md
Labels: enhancement

#45 Resolución del Objetivo Principal
  README.md
Labels: bug

#51 Primary Goal
  README.md
Labels: enhancement
